### ISSUE TITLE
Maestro v2 non-essential roadmap

### ISSUE THREAD

**Issue by Eronne** [FashionData/maestro#227]
- [ ] Empty store on:
  - [ ] Organization change
  - [ ] Workspace change
  - [ ] Sign out
- [ ] Delete organization
- [ ] VeeValidate
  - [ ] Create dynamic form with VeeValidate
  - [ ] Add it on Authentication pages
  - [ ] Add it on Invite members
- [ ] Check unicity of invitation token
- [ ] CI / CD
- [ ] Improve CFs
  - [ ] Create constants for names
  - [ ] Type returns
  - [ ] Check security of CFs
  - [ ] Check authentication / roles
    - [ ] For calling
    - [ ] Of members that we are manipulating
  - [ ] - Return errors when needed
    - [ ] Use i18n locale from user to display error in frontend
  - [ ] CF aliases when importing code from nuxt project
- [ ] Add email templates
- [ ] Invitations improvements
  - [ ] Check if email is already in organization
  - [ ] Check if email is already invited
  - [ ] Invitation expiration (1 week?)
  - [ ] Create and use default value for groupsToInvite in InviteMembersDialogAdd confirmation service to delete invitation
